[package]
name = "Files"
edition = "2021"

[[bin]]
name = "main"
path = "./main.rs"

[dependencies]
bincode = "1.3.3"
serde = "1.0.217"
serde_cbor = "0.11.2"
serde_derive = "1.0.217"
serde_json = "1.0.138"


